name: Node.js CI

on:
  push:
    branches: [ block* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14  # or a more recent version
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependencies
      run: npm ci  # Removed unnecessary directory change
    - name: Build
      run: npm run build --if-present
    - name: Run Tests
      run: npm test
